/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unimet;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class WindowU extends javax.swing.JFrame {
    static List<Student> students;
    static List<Professor> professors;
    ListMethods<Student> printS = (element) -> "Nombre: "+element.getName()+"\nCédula: "+element.getDni()+"\nCarrera: "+element.getCareer()+"\n";
    ListMethods<Professor> printP = (element) -> element.printProfessor();
    /**
     * Creates new form WindowU
     */
    public WindowU() {
        initComponents();
        this.setLocationRelativeTo(null);
        students = new List<>(printS);
        professors = new List<>(printP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameS = new javax.swing.JTextField();
        dniS = new javax.swing.JTextField();
        careerIn = new javax.swing.JTextField();
        nameP = new javax.swing.JTextField();
        dniP = new javax.swing.JTextField();
        subjectIn = new javax.swing.JTextField();
        RegisterProfessor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RegisterStudent = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();
        showStudents = new javax.swing.JButton();
        showProfessors = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("UNIMET - Sirius");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));
        jPanel1.add(nameS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 160, -1));
        jPanel1.add(dniS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 160, -1));
        jPanel1.add(careerIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 160, -1));
        jPanel1.add(nameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 160, -1));
        jPanel1.add(dniP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 160, -1));
        jPanel1.add(subjectIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 160, -1));

        RegisterProfessor.setText("Registrar");
        RegisterProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterProfessorActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 90, -1));

        jLabel3.setText("si quieres registrar un profesor.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel4.setText("Cédula:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setText("Carrera:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel7.setText("Cédula:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel8.setText("Materia:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel9.setText("Completa los siguientes datos ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel10.setText("Nombre:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        RegisterStudent.setText("Registrar");
        RegisterStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterStudentActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 90, -1));

        jLabel11.setText("Completa los siguientes datos ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel12.setText("si quieres registrar un estudiante.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        screen.setBackground(new java.awt.Color(0, 0, 0));
        screen.setColumns(20);
        screen.setRows(5);
        screen.setEnabled(false);
        jScrollPane1.setViewportView(screen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 230, 210));

        showStudents.setText("Ver Estudiantes");
        showStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStudentsActionPerformed(evt);
            }
        });
        jPanel1.add(showStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        showProfessors.setText("Ver Profesores");
        showProfessors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProfessorsActionPerformed(evt);
            }
        });
        jPanel1.add(showProfessors, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        exit.setText("SALIR");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterStudentActionPerformed
        String name = nameS.getText();
        int dni = Integer.parseInt(dniS.getText());
        String career = careerIn.getText();
        Student student = new Student(name, dni, career);
        students.append(student);
        JOptionPane.showMessageDialog(null, "Estudiante reigstrado");
        nameS.setText("");
        dniS.setText("");
        careerIn.setText("");
    }//GEN-LAST:event_RegisterStudentActionPerformed

    private void RegisterProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterProfessorActionPerformed
        String name = nameP.getText();
        int dni = Integer.parseInt(dniP.getText());
        String subject = subjectIn.getText();
        Professor professor = new Professor(name, dni, subject);
        professors.append(professor);
        JOptionPane.showMessageDialog(null, "Profesor reigstrado");
        nameP.setText("");
        dniP.setText("");
        subjectIn.setText("");
    }//GEN-LAST:event_RegisterProfessorActionPerformed

    private void showStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStudentsActionPerformed
        String estudiantes = students.printList();
        screen.setText(estudiantes);
    }//GEN-LAST:event_showStudentsActionPerformed

    private void showProfessorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showProfessorsActionPerformed
        String profesores = professors.printList();
        screen.setText(profesores);
    }//GEN-LAST:event_showProfessorsActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterProfessor;
    private javax.swing.JButton RegisterStudent;
    private javax.swing.JTextField careerIn;
    private javax.swing.JTextField dniP;
    private javax.swing.JTextField dniS;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameP;
    private javax.swing.JTextField nameS;
    private javax.swing.JTextArea screen;
    private javax.swing.JButton showProfessors;
    private javax.swing.JButton showStudents;
    private javax.swing.JTextField subjectIn;
    // End of variables declaration//GEN-END:variables
}
